arxiv:
  ratio:0.0005:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.06
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.8
      temperature: 0.1
      delta: 1.0
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 1.0
      test_acc: 64.7±0.5
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.06
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.8
      temperature: 0.1
      delta: 1.0
      adj_T: 0.9
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 1.0
      test_acc: 64.7±0.1
  ratio:0.0025:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.03
      ot_epochs: 80.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.8
      temperature: 0.5
      delta: 1.0
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 10.0
      test_acc: 68.2±0.1
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.03
      ot_epochs: 80.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.8
      temperature: 0.5
      delta: 1.0
      adj_T: 0.99
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 10.0
      test_acc: 68.2±0.1
  ratio:0.005:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.1
      ot_epochs: 80.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.8
      temperature: 0.1
      delta: 0.5
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 10.0
      test_acc: 68.2±0.2
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.1
      ot_epochs: 80.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.8
      temperature: 0.1
      delta: 0.5
      adj_T: 0.97
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 10.0
      test_acc: 68.2±0.0
