citeseer:
  ratio:0.009:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.1
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.8
      temperature: 0.3
      delta: 0.1
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0001
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 73.9±0.8
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.1
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.8
      temperature: 0.3
      delta: 0.1
      adj_T: 0.9
      noise_level: 0.5
      weight_decay_ot: 0.0001
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 73.9±0.8
  ratio:0.018:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.1
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.8
      temperature: 0.7
      delta: 10.0
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 73.9±0.5
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.1
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.8
      temperature: 0.7
      delta: 10.0
      adj_T: 0.99
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 73.9±0.5
  ratio:0.036:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.2
      ot_epochs: 20.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 4.0
      warmup: 6.0
      dropout: 0.5
      temperature: 0.5
      delta: 2.0
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 2.0
      test_acc: 72.8±0.7
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.2
      ot_epochs: 20.0
      epoch: 600.0
      lr: 0.01
      alpha: 2.0
      update_iter: 4.0
      warmup: 6.0
      dropout: 0.5
      temperature: 0.5
      delta: 2.0
      adj_T: 0.95
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 2.0
      test_acc: 73.0±0.4
