flickr:
  ratio:0.001:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.07
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.5
      temperature: 0.1
      delta: 0.5
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 47.3±0.0
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.07
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.5
      temperature: 0.1
      delta: 0.5
      adj_T: 1.0
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 47.3±0.0
  ratio:0.005:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.07
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.5
      temperature: 0.1
      delta: 2.0
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 47.1±0.0
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.07
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.5
      temperature: 0.1
      delta: 2.0
      adj_T: 1.0
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 47.0±0.1
  ratio:0.01:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.07
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.5
      temperature: 0.1
      delta: 1.0
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 47.1±0.1
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.07
      ot_epochs: 40.0
      epoch: 600.0
      lr: 0.01
      alpha: 1.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.5
      temperature: 0.1
      delta: 1.0
      adj_T: 1.0
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 47.1±0.0
