reddit:
  ratio:0.0005:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.05
      ot_epochs: 40.0
      epoch: 1000.0
      lr: 0.001
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.8
      temperature: 1.0
      delta: 0.5
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 90.7±0.2
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.05
      ot_epochs: 40.0
      epoch: 1000.0
      lr: 0.001
      alpha: 2.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.8
      temperature: 1.0
      delta: 0.5
      adj_T: 0.97
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 90.9±0.1
  ratio:0.001:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.05
      ot_epochs: 40.0
      epoch: 1000.0
      lr: 0.001
      alpha: 10.0
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.7
      temperature: 1.0
      delta: 0.5
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 91.2±0.1
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.05
      ot_epochs: 40.0
      epoch: 1000.0
      lr: 0.001
      alpha: 1.5
      update_iter: 4.0
      warmup: 30.0
      dropout: 0.7
      temperature: 1.0
      delta: 0.5
      adj_T: 0.98
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.1
      test_acc: 91.4±0.1
  ratio:0.002:
    generate_adj:0:
      weight_decay: 0.0005
      epsilon: 0.02
      ot_epochs: 6.0
      epoch: 1000.0
      lr: 0.001
      alpha: 10.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.4
      temperature: 0.3
      delta: 0.2
      adj_T: 0.76
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.2
      test_acc: 91.8±0.1
    generate_adj:1:
      weight_decay: 0.0005
      epsilon: 0.02
      ot_epochs: 6.0
      epoch: 1000.0
      lr: 0.001
      alpha: 3.0
      update_iter: 2.0
      warmup: 2.0
      dropout: 0.4
      temperature: 0.3
      delta: 0.2
      adj_T: 0.995
      noise_level: 0.5
      weight_decay_ot: 0.0005
      lr_ot: 0.0005
      sigma: 0.2
      test_acc: 92.1±0.1
